;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        autopair-insert-opening
        autopair-insert-or-skip-quote
        autopair-skip-close-maybe
        c-electric-brace
        comment-dwim-line
        cua-cut-region
        cua-paste
        delete-indentation
        insert-blank-line-below
        isearch-forward-regexp
        isearch-printing-char
        keyboard-escape-quit
        mc/add-cursor-on-click
        move-text-up
        paredit-close-square
        paredit-open-round
        paredit-open-square
        paredit-splice-sexp-killing-backward
        yas-expand
        ))

(setq mc/cmds-to-run-once
      '(
        iedit-mode
        isearch-other-control-char
        ))
